version: "3.9"
services:
  app:
    restart: always
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: abc123
    ports: 
            - "5432:5432"  
    volumes:
      - ./galenadb.sql:/docker-entrypoint-initdb.d/galenadb.sql
    networks:
      - backend

networks:
  backend:
    driver: bridge
    name: ganela-network